package statuspage

import (
	"strings"
	"text/template"
)

var textTemplate *template.Template

func init() {
	content := `
{{ .Code }} {{ .Text }}

{{ .Message }}

Generated by Rinq.
http://rinq.io
`

	textTemplate = template.Must(
		template.New("status-page").Parse(strings.TrimSpace(content)),
	)
}
