package statuspage

import (
	"html/template"
	"strings"
)

var htmlTemplate *template.Template

func init() {
	content := `
<!DOCTYPE html>
<html>
    <head>
        <title>{{ .Code }} {{ .Text }}</title>
        <link href="https://fonts.googleapis.com/css?family=Yantramanav:100" rel="stylesheet">
        <style>
            body {
                background: white;
                font-family: 'Yantramanav', sans-serif;
                font-weight: 100;
                font-size: 3.8vmin;
            }

            div {
                text-align: center;
                height: 36vh;
                position: absolute;
                top: 0;
                bottom: 0;
                left: 0;
                right: 0;
                margin: auto;
            }

            h1, h2 {
                margin: 1.5vmin;
                padding: 0;
                display: inline;
                font-weight: 100;
                font-size: 20vmin;
            }

            h1 {
                font-size: 6vmin;
                text-transform: uppercase;
                white-space: nowrap;
            }

            p {
                padding: 0;
                color: gray;
            }

            footer {
                position: absolute;
                bottom: 0;
                right: 0;
                color: gray;
                font-size: 2vmin;
                text-align: right;
                margin: 1vmin;
            }

            a {
                text-decoration: none;
                color: black;
            }

            a:hover {
                text-decoration: underline;
            }
        </style>
    </head>
    <body>
        <div>
            <header>
                <h2>{{ .Code }}</h2>
                <h1>{{ .Text }}</h1>
            </header>
            <p>{{ .Message }}</p>
        </div>
		<footer>Generated by <a href="http://rinq.io">Rinq</a>.</footer>
    </body>
</html>
`

	htmlTemplate = template.Must(
		template.New("status-page").Parse(strings.TrimSpace(content)),
	)
}
